apiVersion: v1
kind: Service
metadata:
  name: game-2048
  namespace: default
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
  selector:
    app: game-2048

# apiVersion: v1
# kind: Service
# metadata:
#   name: django-service
#   namespace: default
# spec:
#   selector:
#     app: django-app
#   ports:
#     - protocol: TCP
#       port: 80
#       targetPort: 8000
#   type: NodePort
